// Generates dist-bound token artifacts from the single source of truth
// (tokens.json) so the CSS variables and the JS object can never drift.
//   tokens.json  ->  src/tokens.css   (CSS custom properties on :root)
//                ->  src/tokens.js     (flat camelCase JS object `tokens`)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const tokens = JSON.parse(readFileSync(join(root, "tokens.json"), "utf8"));

// CSS variable prefix per group ("" = bare color names like --bg).
const CSS_PREFIX = {
  color: "",
  font: "font-",
  text: "fs-",
  space: "sp-",
  radius: "r-",
  shadow: "shadow-",
  z: "z-",
};

const camel = (s) =>
  s
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w, i) => (i === 0 ? w : w[0].toUpperCase() + w.slice(1)))
    .join("");

const cssLines = [];
const jsEntries = [];

for (const [group, entries] of Object.entries(tokens)) {
  const prefix = CSS_PREFIX[group] ?? `${group}-`;
  for (const [name, value] of Object.entries(entries)) {
    const cssName = `--${prefix}${name}`;
    cssLines.push(`  ${cssName}: ${value};`);
    jsEntries.push([camel(`${prefix}${name}`), value]);
  }
}

const cssOut = `/* GENERATED by scripts/gen-tokens.mjs — edit tokens.json instead. */\n:root {\n${cssLines.join("\n")}\n}\n`;

const jsOut =
  `/* GENERATED by scripts/gen-tokens.mjs — edit tokens.json instead. */\n` +
  `export const tokens = {\n` +
  jsEntries.map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`).join("\n") +
  `\n};\nexport default tokens;\n`;

mkdirSync(join(root, "src"), { recursive: true });
writeFileSync(join(root, "src", "tokens.css"), cssOut);
writeFileSync(join(root, "src", "tokens.js"), jsOut);
console.log(`gen-tokens: wrote ${jsEntries.length} tokens to src/tokens.css and src/tokens.js`);
